### ISSUE TITLE
Warning if Encyclopedia Pro is installed

### ISSUE THREAD

**Issue by MatzeKitt** [epiphyt/embed-privacy#15]
```
ErrorException: Warning: Creating default object from empty value
#8 /wp-content/plugins/encyclopedia-pro/classes/updates.php(160): WordPress\Plugin\Encyclopedia\Updates::filterUpdatePlugins
#7 /wp-includes/class-wp-hook.php(289): WP_Hook::apply_filters
#6 /wp-includes/plugin.php(212): apply_filters
#5 /wp-includes/option.php(1899): get_site_transient
#4 /wp-includes/update.php(667): wp_get_translation_updates
#3 /wp-includes/update.php(729): wp_get_update_data
#2 /wp-admin/menu.php(33): require
#1 /wp-admin/admin.php(158): require_once
#0 /wp-admin/post.php(12): null
```

**Comment by MatzeKitt** [comment]
This is a different error message than the one we’ve got privately. This is the actual problematic one and has been fixed with 128d5dde773fc372200d7c4cf38821807baa8bb5:

```
[13-Jan-2021 12:16:15 UTC] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to WordPress\Plugin\Encyclopedia\Content_Filter::addRelatedItems() must be of the type string, null given, called in /wp-includes/class-wp-hook.php on line 287 and defined in /wp-content/plugins/encyclopedia-pro/classes/content-filter.php:36
Stack trace:
#0 /wp-includes/class-wp-hook.php(287): WordPress\Plugin\Encyclopedia\Content_Filter::addRelatedItems(NULL)
#1 /wp-includes/plugin.php(212): WP_Hook->apply_filters(NULL, Array)
#2 /wp-content/plugins/wordpress-seo-premium/src/builders/indexable-link-builder.php(87): apply_filters('the_content', 'Click here to d...')
#3 /wp-content/plugins/wordpress-seo-premium/src/integrations/watchers/indexable-post-watcher.php(170): Yoast\WP\SEO\Builders\Indexable_Link_Builder->build(Object(Yoast\WP\SEO\Models\Indexable), 'Click here to d...')
#4 / in /wp-content/plugins/encyclopedia-pro/classes/content-filter.php on line 36
```

The above one is during site transients, which have nothing to do with our plugin, since we don’t do anything there. Thus, I will close this issue.
