### ISSUE TITLE
Warning: Attempt to read property "public" on null

### ISSUE THREAD

**Issue by MatzeKitt** [epiphyt/embed-privacy#222]
### Bug/Problem

```
ErrorException: Warning: Attempt to read property "public" on null
#9 /wp-includes/rewrite.php(620): url_to_postid
#8 /wp-content/plugins/embed-privacy/inc/class-embed-privacy.php(1749): epiphyt\Embed_Privacy\Embed_Privacy::register_assets
#7 /wp-includes/class-wp-hook.php(324): WP_Hook::apply_filters
#6 /wp-includes/class-wp-hook.php(348): WP_Hook::do_action
#5 /wp-includes/plugin.php(517): do_action
#4 /wp-settings.php(695): require_once
#3 /wp-config.php(191): require_once
#2 /wp-load.php(50): require_once
#1 /wp-blog-header.php(13): require
#0 /index.php(17): null
```

### Steps to reproduce

Not sure yet.

### Version

Current

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MatzeKitt** [comment]
Comes from a post with post status `dp-rewrite-republish`, so seems to be an issue with Duplicate Post.
