### ISSUE TITLE
Fatal error on uninstall

### ISSUE THREAD

**Issue by Zodiac1978** [epiphyt/embed-privacy#49]
I get a fatal error on the uninstall routine:

```
[23-Mar-2021 13:15:20 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function epiphyt\Embed_Privacy\get_sites() in /wp-content/plugins/embed-privacy/uninstall.php:22
Stack trace:
#0 /wp-admin/includes/plugin.php(1262): include_once()
#1 /wp-admin/includes/plugin.php(967): uninstall_plugin('embed-privacy/e...')
#2 /wp-admin/includes/ajax-actions.php(4581): delete_plugins(Array)
#3 /wp-includes/class-wp-hook.php(292): wp_ajax_delete_plugin('')
#4 /wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters('', Array)
#5 /wp-includes/plugin.php(484): WP_Hook->do_action(Array)
#6 /wp-admin/admin-ajax.php(187): do_action('wp_ajax_delete-...')
#7 {main}
  thrown in /wp-content/plugins/embed-privacy/uninstall.php on line 22
```

**Comment by Zodiac1978** [comment]
Looks like there is this line in uninstall.php missing:
`use function get_sites;`

**Comment by MatzeKitt** [comment]
`get_sites` is only available for multisites. Additionally to the use statement, the check for multisites is missing.

**Comment by MatzeKitt** [comment]
This will be fixed in the upcoming bugfix release.
